export const CODE_FILE_TYPES: Record<string, string> = {
  'text/html': 'html',
  'application/html': 'html',
  'text/css': 'css',
  'application/css': 'css',
  'text/javascript': 'javascript',
  'application/javascript': 'javascript',
  'application/x-javascript': 'javascript',
  'text/ecmascript': 'javascript',
  'application/ecmascript': 'javascript',
  'text/babel': 'javascript',
  'text/jsx': 'jsx',
  'application/jsx': 'jsx',
  'text/x-jsx': 'jsx',
  'application/typescript': 'typescript',
  'text/typescript': 'typescript',
  'text/x-typescript': 'typescript',
  'application/x-typescript': 'typescript',
  'text/tsx': 'tsx',
  'application/tsx': 'tsx',
  'text/x-tsx': 'tsx',
  'application/x-tiled-tsx': 'tsx',
  'application/json': 'json',
  'text/json': 'json',
  'application/x-json': 'json',
  'application/manifest+json': 'json',
  'application/ld+json': 'json',
  'text/x-python': 'python',
  'application/x-python': 'python',
  'application/x-python-code': 'python',
  'text/x-python-script': 'python',
  'application/x-httpd-php': 'php',
  'text/x-php': 'php',
  'application/php': 'php',
  'text/x-ruby': 'ruby',
  'application/x-ruby': 'ruby',
  'text/ruby': 'ruby',
  'text/x-sh': 'bash',
  'text/x-shellscript': 'shell',
  'application/x-sh': 'bash',
  'text/x-c': 'c',
  'text/x-csrc': 'c',
  'text/x-chdr': 'c',
  'text/x-c++': 'cpp',
  'text/x-c++src': 'cpp',
  'text/x-c++hdr': 'cpp',
  'text/x-java': 'java',
  'text/x-java-source': 'java',
  'text/x-go': 'go',
  'text/x-golang': 'go',
  'text/x-rust': 'rust',
  'text/rust': 'rust',
  'text/x-kotlin': 'kotlin',
  'text/kotlin': 'kotlin',
  'text/x-swift': 'swift',
  'text/swift': 'swift',
  'text/x-scala': 'scala',
  'text/scala': 'scala',
  'text/x-perl': 'perl',
  'application/x-perl': 'perl',
  'text/x-lua': 'lua',
  'application/x-lua': 'lua',
  'text/xml': 'xml',
  'application/xml': 'xml',
  'text/x-yaml': 'yaml',
  'application/x-yaml': 'yaml',
  'text/yaml': 'yaml',
  'text/x-toml': 'toml',
  'application/toml': 'toml',
  'text/x-ini': 'ini',
  'text/ini': 'ini',
  'text/x-properties': 'properties',
  'text/x-java-properties': 'properties',
  'text/csv': 'csv',
  'application/csv': 'csv',
  'text/x-csv': 'csv',
  'text/x-sql': 'sql',
  'application/sql': 'sql',
  'text/x-mysql': 'sql',
  'text/x-pgsql': 'sql',
  'text/markdown': 'markdown',
  'text/x-markdown': 'markdown',
  'text/md': 'markdown',
  'text/x-md': 'markdown',
  'text/x-rst': 'rest',
  'text/x-latex': 'latex',
  'application/x-latex': 'latex',
  'application/x-tex': 'latex',
  'text/x-haskell': 'haskell',
  'text/x-literate-haskell': 'haskell',
  'text/x-erlang': 'erlang',
  'text/x-elixir': 'elixir',
  'text/x-clojure': 'clojure',
  'text/x-fsharp': 'fsharp',
  'text/x-r': 'r',
  'text/r': 'r',
  'text/x-matlab': 'matlab',
  'text/x-octave': 'matlab',
  'text/x-dart': 'dart',
  'application/dart': 'dart',
  'text/x-groovy': 'groovy',
  'text/groovy': 'groovy',
  'text/x-julia': 'julia',
  'text/x-wasm': 'wasm',
  'application/wasm': 'wasm',
  'application/graphql': 'graphql',
  'text/x-graphql': 'graphql',
  'text/x-protobuf': 'protobuf',
  'application/x-protobuf': 'protobuf',
  'text/x-dockerfile': 'dockerfile',
  'application/vnd.docker.dockerfile': 'dockerfile',
  'text/x-git-config': 'git',
  'text/x-git': 'git',
  'text/x-scss': 'scss',
  'text/scss': 'scss',
  'text/x-sass': 'sass',
  'text/sass': 'sass',
  'text/x-less': 'less',
  'text/less': 'less',
  'text/x-handlebars': 'handlebars',
  'text/x-mustache': 'mustache',
  'text/x-ejs': 'javascript',
  'text/x-nunjucks': 'javascript',
  'text/x-vue': 'html',
  'text/vue': 'html',
  'text/x-svelte': 'html',
  'text/svelte': 'html',
  'text/x-blade': 'php',
  'text/blade': 'php',
  'text/x-twig': 'twig',
  'text/twig': 'twig',
  'text/x-jinja': 'jinja2',
  'text/jinja': 'jinja2',
  'text/x-velocity': 'velocity',
  'text/velocity': 'velocity',
  'text/x-asm': 'asm6502',
  'text/x-nasm': 'nasm',
  'text/x-masm': 'nasm',
  'text/x-gas': 'nasm',
}

export const TEXT_FILE_TYPES = ['text/plain', 'text/rtf', 'text/x-log']

export const VIDEO_FILE_TYPES = [
  'video/mp4',
  'video/webm',
  'video/ogg',
  'video/quicktime',
  'video/x-msvideo',
  'video/x-matroska',
  'video/x-flv',
  'video/3gpp',
  'video/3gpp2',
]

export const AUDIO_FILE_TYPES = [
  'audio/mpeg',
  'audio/ogg',
  'audio/wav',
  'audio/webm',
  'audio/aac',
  'audio/x-m4a',
  'audio/x-flac',
  'audio/x-aiff',
  'audio/x-wav',
]

export const MAX_CSV_SIZE = 1024 * 1024
